### ISSUE TITLE
Error di Detail Siswa

### ISSUE THREAD

**Issue by Richelle-Vallery-Tando** [rezafikkri/manport#2]
Sebelumnya saya ingin mengucapkan terimakasih Kak atas codenya. Saya sudah mencobanya tetapi untuk bagian detal siswa tidak bisa ditambahkan Kak, sudah saya pencet tombol hijaunya, isinya hanya tambah siswa kemudian tidak ada command lagi.

**Comment by rezafikkri** [comment]
pakai php versi berapa?

**Comment by Richelle-Vallery-Tando** [comment]
Versi 7.4 Kak

Pada tanggal Kam, 19 Jan 2023 14:01, Reza Sariful Fikri <
***@***.***> menulis:

**Comment by rezafikkri** [comment]
boleh kirimkan screenshot halaman errornya? screenshot halaman biasa dengan screenshot halaman viewpage source

**Comment by Richelle-Vallery-Tando** [comment]
[image: image.png]

Pada tanggal Min, 22 Jan 2023 pukul 02.34 Reza Sariful Fikri <
***@***.***> menulis:

**Comment by Richelle-Vallery-Tando** [comment]
Seperti itu kak, sudha klik button hijau, tidak bisa add siswa, saya coba
add di phpnya sendiri juga tidak bisa.
Maaf Kak baru balas

Pada tanggal Sen, 23 Jan 2023 pukul 22.25 Richelle Vallery <
***@***.***> menulis:

**Comment by rezafikkri** [comment]
coba kirimkan screenshotnya ke email aja, enggak kekirim soalnya. emailnya : rezafikkri@gmail.com
