### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by avinakefin** [rezafikkri/manport#3]
![Screenshot_20230609-184907_Chrome](https://github.com/rezafikkri/Manport/assets/12618220/ce0329c0-f2a3-4ec8-b03c-9b7cc6c18e04)

ID Login apa bang ? 
Saya pakai yg di readme 
u : reza 
P : reza12345678
Ndak bisa coba admin admin Ndak bisa coba reza admin Ndak bisa

**Comment by rezafikkri** [comment]
Salah tempat loginnya mas, itu form untuk login guru wali kelas kalau mau
mengisi nilai raport siswa, untuk admin ada di /admin

**Comment by avinakefin** [comment]
Oalah ok om saya coba

**Comment by avinakefin** [comment]
Wuih bisa om 😁
