### ISSUE TITLE
mohon bantuannya

### ISSUE THREAD

**Issue by fhusnaini** [rezafikkri/manport#4]
sy baru menggunakan man raport untuk sekolah. mohon kk ditambahin untuk akses guru yang mengajar bidang study pelajaran yang berhak menginput nilainya. sedangkan wali kelas hanya bisa mencetak raport nya. 
terima kasih kk

**Comment by rezafikkri** [comment]
Mohon maaf, karena ini memang sedikit berbeda dengan konsep aplikasinya. Dalam aplikasi ini konsep nya adalah, para guru mata pelajaran menyerahkan nilai mapelnya ke wali kelas dan wali kelas yang mengisi raportnya.

Mohon maaf, saya ingin berdiskusi juga. Disekolahnya kamu, proses manual pengisian raport siswanya bagaimana biasanya? apakah file raportnya di serahkan secara bergantian ke guru mata pelajarannya untuk disisi nilai? lalu kalau sudah terkumpul semua, maka guru tinggal print raportnya?

Atau guru mapelnya menyerahkan nilai ke wali kelas, dan wali kelas yang akan mengisi raportnya?

**Comment by fhusnaini** [comment]
oo.. klo dilihat dari manport memang benar. tetapi baiknya guru mata pelajaran yang memasukkan nilai diraportnya. sedangkan wali kelas hanya menerima raport & untuk cetak rapot wali kelas. 

klo proses manualnya ya betul konsepnya. Barang kali jika pakai aplikasi baiknya guru mapel sendiri yang input nilai sedangkan wali kelas hanya mencetak hasil rapot aja. jadi wali kelas tidak bisa merubah nilai yang diberikan oleh guru mata pelajaran.

**Comment by rezafikkri** [comment]
emm oke mas, terimakasih untuk sarannya, tetapi dalam waktu dekat, sepertinya tidak bisa saya tambahkan fitur tersebut, karena saya masih ada kesibukan lain.

**Comment by fhusnaini** [comment]
siap terima kasih kk
